# hardware abstraction layer
# custom code that exposes standard functions for specific hardware
hal_module: telescope_cdk700
hal_class: Cdk700

# connection info
host: '192.168.1.3'
port: 44444

instrument:
  - spectrograph_kiwispec.yaml
  - camera_andor1.yaml

